language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.9.9
  - DJANGO=1.8.14
  - DJANGO=1.10

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.9.9
    - python: "3.3"
      env: DJANGO=1.10

install:
  - pip install Django==$DJANGO times
  - python setup.py install

script: make test
services: redis
